version: '3.1'

services: 
 cent:
  build:
   context: ./
   dockerfile: Dockerfile-centos
  ports:
  - "8082:80"
  volumes:
  - data-volume:/home/data
  entrypoint: /usr/sbin/httpd -D FOREGROUND
 nginx:
  build:
   context: ./
   dockerfile: Dockerfile-nginx
  ports:
   - "8083:80"
  entrypoint: nginx -g 'daemon off;'

volumes:
 data-volume:
