version: '3.1'

services: 
 cent:
  build: .
  ports:
  - "8082:80"
  volumes:
  - data-volume:/home/data
  entrypoint: top -c -b
 nginx:
  image: "nginx:latest"
  ports:
  - "8083:80"

volumes:
 data-volume:
